# Generated by Django 4.2.4 on 2023-08-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pincode',
            field=models.IntegerField(default=None),
        ),
    ]
