# Generated by Django 4.2.4 on 2023-08-16 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_person_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
    ]
